#ifndef RESOURCE_H
#define RESOURCE_H

#define IDI_APPICON    100

#define IDB_BOARD      200
#define IDB_SELECTED   201
#define IDB_RK         208
#define IDB_RA         209
#define IDB_RB         210
#define IDB_RN         211
#define IDB_RR         212
#define IDB_RC         213
#define IDB_RP         214
#define IDB_BK         216
#define IDB_BA         217
#define IDB_BB         218
#define IDB_BN         219
#define IDB_BR         220
#define IDB_BC         221
#define IDB_BP         222

#define IDR_CLICK      300
#define IDR_ILLEGAL    301
#define IDR_MOVE       302
#define IDR_MOVE2      303
#define IDR_CAPTURE    304
#define IDR_CAPTURE2   305
#define IDR_CHECK      306
#define IDR_CHECK2     307
#define IDR_WIN        308
#define IDR_DRAW       309
#define IDR_LOSS       310

#define IDM_MAINMENU   400
#define IDM_FILE_RED   401
#define IDM_FILE_BLACK 402
#define IDM_FILE_EXIT  403
#define IDM_HELP_HOME  404
#define IDM_HELP_ABOUT 405

#endif
